/*
 * generated by Xtext 2.9.1
 */
package it.polimi.xtext.tosca4cloudifydsl.ui.tests;

import com.google.inject.Injector;
import it.polimi.xtext.tosca4cloudifydsl.ui.internal.Tosca4cloudifydslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Tosca4cloudifydslActivator.getInstance().getInjector("it.polimi.xtext.tosca4cloudifydsl.Dsl");
	}

}
