/**
 * generated by Xtext 2.9.1
 */
package it.polimi.xtext.tosca4cloudifydsl.validation;

import it.polimi.xtext.tosca4cloudifydsl.validation.AbstractDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
