/**
 * generated by Xtext 2.9.1
 */
package it.polimi.xtext.tosca4cloudifydsl.ui;

import it.polimi.xtext.tosca4cloudifydsl.ui.AbstractDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  public DslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
