/**
 * generated by Xtext 2.9.1
 */
package it.polimi.xtext.tosca4cloudifydsl.ui.contentassist;

import it.polimi.xtext.tosca4cloudifydsl.ui.contentassist.AbstractDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
