/*
 * generated by Xtext 2.9.1
 */
package it.polimi.xtext.tosca4cloudifydsl.ui;

import com.google.inject.Injector;
import it.polimi.xtext.tosca4cloudifydsl.ui.internal.Tosca4cloudifydslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Tosca4cloudifydslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Tosca4cloudifydslActivator.getInstance().getInjector(Tosca4cloudifydslActivator.IT_POLIMI_XTEXT_TOSCA4CLOUDIFYDSL_DSL);
	}
	
}
